### ISSUE TITLE
vscode报错 No module named 'config_component'

### ISSUE THREAD

**Issue by Mantoufly** [Tianyi822/bilibili_buy_ticket#1]
我是用windows上的vscode运行的，这个是文件路径问题吗，我看config下面标注了Linux。

**Comment by Tianyi822** [comment]
你可以把 `replace('\\', '/')` 这个代码删掉，因为在linux下，文件路径是以 / 切分的，windows是 \

**Comment by Mantoufly** [comment]
> 你可以把 `replace('\\', '/')` 这个代码删掉，因为在linux下，文件路径是以 / 切分的，windows是 \

这个我也尝试过，包括直接使用绝对路径
![image](https://github.com/Tianyi822/bilibili_buy_ticket/assets/97418696/414208ba-5147-4260-89e8-1d44b6e538c9)
呜呜呜，我就想去bw，人工抢不到，呜呜呜

**Comment by Tianyi822** [comment]
你这不是路径问题，是项目运行过程中，没找到config_component包，你是不是把config_component里面的__init__.py删除了

**Comment by Mantoufly** [comment]
> 你这不是路径问题，是项目运行过程中，没找到config_component包，你是不是把config_component里面的__init__.py删除了

没有删除，我知道这个__init__.py的作用，每个文件里面都有这个文件，我没有动目录结构，只进行了对应配置修改，还就是你刚刚说的删除replace

**Comment by Tianyi822** [comment]
我这里在windows 上测试了，没问题，你加我一个qq：717635744

**Comment by Healock** [comment]
可复现

**Comment by Tianyi822** [comment]
已经修复了

**Comment by Mantoufly** [comment]
> 可复现

![A`T%WZN21EXZRZZSKYOJ)SJ](https://github.com/Tianyi822/bilibili_buy_ticket/assets/97418696/98dda5cd-cb2b-41bc-a905-aa855c76643f)
试一试

**Comment by smxcbql** [comment]
也是这个问题，这要怎么解决啊

**Comment by smxcbql** [comment]
打开了run界面但是它不跑嘞
